### ISSUE TITLE
0 of 0 tests?

### ISSUE THREAD

**Issue by rgwch** [dbashford/MimosaTestem#1]
I am not sure if I'm getting something completely wrong (new to Mimosa). While this sample app compiles and runs perfectly, it does not seem to test anything.

The output of `mimosa watch -s` is:

```
18:06:22 - Info - Did not find compiled directory public, so making it for you
18:06:22 - Info - Watching assets
18:06:22 - Success - Wrote file public/javascripts/main.js  
18:06:24 - Success - Wrote file public/javascripts/app/repo-view.js
18:06:24 - Success - Wrote file public/javascripts/specs/repo-view_spec.js 
18:06:24 - Success - Wrote file public/javascripts/vendor/jquery.js
18:06:24 - Success - Wrote file public/javascripts/specs/data-helper.js
18:06:24 - Success - Wrote file public/javascripts/vendor/lodash.js
18:06:24 - Success - Wrote file public/javascripts/vendor/moment.js
18:06:24 - Success - Wrote file public/javascripts/vendor/require.js
18:06:24 - Success - Wrote file public/stylesheets/style.css
18:06:24 - Success - Wrote file public/javascripts/templates.js
18:06:24 - Success - Wrote file public/javascripts/vendor/handlebars.js
18:06:25 - Success - Mimosa is starting your server: server.coffee
Express server listening on port 3000
18:06:26 - Success - 0 of 0 tests passed for .mimosa/testemRequire/testem.json.
```

0 tests is less than I expected. How can run the tests?

**Comment by dbashford** [comment]
So I did a fresh install of all the stuff in `node_modules`, and a fresh install of `npm install -g phantomjs` and it all worked.  Any chance you don't have phantom installed?

![image](https://cloud.githubusercontent.com/assets/581127/8257661/6985e614-167d-11e5-8ebe-e2c8fd0cfee3.png)

**Comment by rgwch** [comment]
Stupid me. I had installed phantomjs  in my project, but not globally, and so it wasn't found here. 
My apologies for wasting your time. And thanks for your help!

**Comment by dbashford** [comment]
:+1: 

No harm done. I happen to be digging into a ton of testem related stuff this week, so it was easy to check out. =)
